name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-static-site:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Pull the latest Docker image for your website
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-static-site:latest

            # 2. Stop and remove any existing Nginx container
            docker stop my-static-site || true
            docker rm my-static-site || true
            
            # Stop and remove any existing Certbot container
            docker stop certbot || true
            docker rm certbot || true

            # 3. Create a shared network
            docker network create webapp-network || true

            # 4. Create the necessary Docker volumes
            docker volume create --name=certbot_certs
            docker volume create --name=certbot_webroot

            # 5. Start the Nginx container
            docker run -d \
              --name my-static-site \
              --network webapp-network \
              -p 80:80 \
              -p 443:443 \
              -v certbot_certs:/etc/letsencrypt \
              -v certbot_webroot:/var/www/html \
              ${{ secrets.DOCKERHUB_USERNAME }}/my-static-site:latest
              
            # 6. Run the Certbot container to handle renewals
            docker run -d \
              --name certbot \
              --network webapp-network \
              -v certbot_certs:/etc/letsencrypt \
              -v certbot_webroot:/var/www/html \
              certbot/certbot \
              renew --dry-run # Initially run with --dry-run to test

            echo "Deployment complete. Check your website and logs."