name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-static-site:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Debug Nginx Container Startup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          shell: bash -lce " {0} " # Keep this for robustness
          script: |
            # 1. Pull the latest Docker image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-static-site:latest
  
            # 2. Stop and remove any existing container named 'my-static-site'
            docker stop my-static-site || true
            docker rm my-static-site || true
  
            # 3. Temporarily run the new container in foreground to see startup logs
            # REMOVED -d flag. Container will run until it exits or you stop the job.
            # ALSO REMOVED all subsequent commands for now (copy, perm, reload, rename)
            echo "Starting container in foreground to capture logs..."
            docker run \
              -p 80:80 \
              -p 443:443 \
              --name my-static-site-debug \
              ${{ secrets.DOCKERHUB_USERNAME }}/my-static-site:latest
  
            # If the container exits quickly, its logs will appear here.
            # If it stays running, you will need to manually stop the GitHub Actions job.
